/*
Levels are generated by ascii characters in the level_data array.
# = border
@ = player location
O = next level portal
K[unique_id] = key
D[unique_id] = door
*/
var level_data = [
  [
    '############################################',
    '#                                         O#',
    '######D[1]#####################################',
    '#      #           K[3]       #               #',
    '#      #                   D[3]               #',
    '#      #                   #             K[2] #',
    '#  #####          ##########################',
    '#                                 #        #',
    '#@ #####                          D[2]     K[1]  #',
    '############################################',
  ],
  [
    '################',
    '#             O#',
    '######D[2]#########',
    '#           K[2]  #',
    '######D[1]#########',
    '#              #',
    '#@          K[1]  #',
    '################'
  ]
];
var game_data = {
  lvl: 0,
  lvl_loaded: false
};
var game_keys = [];
function createLevel(lvl) {
  var tbl = document.createElement('table');
  tbl.id = 'current_game_table';
  for (var i=0; i<level_data[lvl].length; i++) {
    var row = tbl.insertRow(-1);
    for (var i2=0; i2<level_data[lvl][i].length; i2++) {
      var cell = row.insertCell(-1);
      if (level_data[lvl][i][(i2+1)] !== null && level_data[lvl][i][(i2+1)] == '[') {
        var id_out = '';
        var save_type = level_data[lvl][i][i2];
        i2 += 2;
        while (level_data[lvl][i][i2] != ']') {
          id_out += level_data[lvl][i][i2];
          i2++;
        }
        cell.id = save_type+'_'+id_out;
        cell.className = 'type_'+save_type;
      } else if (level_data[lvl][i][i2] == 'O') {
        cell.id = 'end';
        cell.className = 'end';
      } else if (level_data[lvl][i][i2] == '#') {
        cell.className = 'border';
      } else if (level_data[lvl][i][i2] == '@') {
        cell.innerHTML = level_data[lvl][i][i2];
        cell.id = 'player';
      }
    }
  }
  document.body.appendChild(tbl);
}

function hitDetect(elem) {
  if (elem.className == 'border') {
    return false;
  }
  if (elem.className == 'type_D') {
    var d = parseInt(elem.id.split("_")[1]);
    if (game_keys[d] == true) {
      elem.className = '';
      elem.id = '';
      elem.innerHTML = '';
    } else {
      return false;
    }
  }
  if (elem.className == 'type_K') {
    game_keys[parseInt(elem.id.split("_")[1])] = true;
    elem.className = '';
    elem.id = '';
    elem.innerHTML = '';
  }
  if (elem.className == 'end') {
    game_data["lvl"]++;
    game_keys = [];
    document.getElementById("current_game_table").remove();
    createLevel(game_data["lvl"]);
  }
  return true;
}

function findColDiffRow(p,s) {
  var c = p.children;
  var found = false;
  for (var i=0; i<c.length; i++) {
    if (c[i].id == 'player') {
      found = true;
      break;
    }
  }
  if (found == false) {
    return false;
  } else {
    var n = (s == 1 ? p.previousSibling.children[i] : p.nextSibling.children[i]);
    if (!hitDetect(n)) {
      return false; 
    } else {
      return n;
    }
  }
}

createLevel(game_data["lvl"]);

document.addEventListener('keydown', function (e) {
  var player = document.getElementById("player");
  if (e.keyCode == 37) {
    if (hitDetect(player.previousSibling)) {
      player.id = '';
      player.innerHTML = '';
      player.previousSibling.id = 'player';
      player.previousSibling.innerHTML = '@';    
    }
  } else if (e.keyCode == 38) {
     var scdr = findColDiffRow(player.parentNode,1);
     if (scdr != false) {
        player.id = '';
       player.innerHTML = '';
       scdr.id = 'player';
       scdr.innerHTML = '@';
     }
  } else if (e.keyCode == 39) {
    if (hitDetect(player.nextSibling)) {
      player.id = '';
      player.innerHTML = '';
      player.nextSibling.id = 'player';
      player.nextSibling.innerHTML = '@';    
    }
  } else if (e.keyCode == 40) {
    var scdr = findColDiffRow(player.parentNode,0);
    if (scdr != false) {
      player.id = '';
      player.innerHTML = '';
      scdr.id = 'player';
      scdr.innerHTML = '@';
    }        
  }
});